### ISSUE TITLE
UI/UX: Error messages should be more prominent

### ISSUE THREAD

**Issue by jhermann** [mislavcimpersak/xkcd-excuse-front#8]
Add some image at the top. use white on red instead of red on white, etc.

I thought stuff is not working, until I noticed the tiny pale red text. ;)

**Comment by mislavcimpersak** [comment]
Regarding error text:

Did you think something like this?

<img width="895" alt="screenshot 2017-11-30 19 31 06" src="https://user-images.githubusercontent.com/3473617/33448060-4d6308d2-d605-11e7-9101-2ace45909b32.png">

This is a bit too much for my taste :suspect: 

In #9 I've increased the font size for error text. That should help :)

<img width="172" alt="screenshot 2017-11-30 19 36 27" src="https://user-images.githubusercontent.com/3473617/33448425-4e4c8362-d606-11e7-9380-787c60ad99c9.png">
<img width="168" alt="screenshot 2017-11-30 19 35 26" src="https://user-images.githubusercontent.com/3473617/33448423-4e123a86-d606-11e7-9533-21f744526433.png">

**Comment by mislavcimpersak** [comment]
Regarding this suggestion:

> Add some image at the top.

What kind of image did you have in mind? I'm not sure what kind of image would be appropriate here? Also, if I put image at the top the user would have to scroll through that image to get to the form 🤕

**Comment by jhermann** [comment]
Doesn't need to be at the top, something like :warning:, :stop_sign:, or :x: before the error messages will also attract eyes.

**Comment by mislavcimpersak** [comment]
something like one of these?

<img width="138" alt="screenshot 2017-12-01 09 19 02" src="https://user-images.githubusercontent.com/3473617/33473979-eb795b7a-d678-11e7-9817-a2db875e303d.png">
<img width="141" alt="screenshot 2017-12-01 09 19 32" src="https://user-images.githubusercontent.com/3473617/33473980-eb91f8c4-d678-11e7-8910-4e088ebf8d94.png">
<img width="141" alt="screenshot 2017-12-01 09 20 24" src="https://user-images.githubusercontent.com/3473617/33473982-ebab69a8-d678-11e7-87a5-06ac8ad9b15e.png">

**Comment by mislavcimpersak** [comment]
or my favorite:

<img width="139" alt="screenshot 2017-12-01 09 23 30" src="https://user-images.githubusercontent.com/3473617/33474092-55b6b30c-d679-11e7-96f7-20c85a1aac0c.png">


😀

**Comment by jhermann** [comment]
Well, from the std GH emojis, :x: is the most fitting one.

**Comment by mislavcimpersak** [comment]
But is it the really _the best_ one?

Bare in mind that this is a fun and mostly pointless project 😁

**Comment by jhermann** [comment]
Well, if you put it that way, then :middle_finger: comes to mind. :grimacing:

**Comment by mislavcimpersak** [comment]
What? Dude. Giving a user the middle finger is never an option. 🤕
